function tideSwanseaMac =get_tide_Swansea()
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/linnemelieschaffer/Dropbox/Masteroppgave/Matlab/Tidevannskonstanter.xlsx
%    Worksheet: Harmonic components
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/03 16:56:08

%% Import the data
[~, ~, raw] = xlsread('/Users/linnemelieschaffer/Dropbox/Masteroppgave/Matlab/Tidevannskonstanter.xlsx','Harmonic components');
raw = raw(17:end,11:14);

%% Create output variable
TidevannskonstanterS1 = reshape([raw{:}],size(raw));
tideSwanseaMac=TidevannskonstanterS1;

%% Clear temporary variables
clearvars raw;
end