%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: \\file.stud.iot.ntnu.no\Home\linnesc\Documents\Masteroppgave\Matlab\Copy of Tidevannskonstanter.xlsx
%    Worksheet: Harmonic components
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/04 09:52:15

function tideSwansea =get_tide_Swansea_School()

%% Import the data
[~, ~, raw] = xlsread('\\file.stud.iot.ntnu.no\Home\linnesc\Documents\Masteroppgave\Matlab\Copy of Tidevannskonstanter.xlsx','Harmonic components','L19:O22');

%% Create output variable
CopyofTidevannskonstanterS1 = reshape([raw{:}],size(raw));
tideSwansea=CopyofTidevannskonstanterS1;
%% Clear temporary variables
clearvars raw;
end