%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: \\file.stud.iot.ntnu.no\Home\linnesc\Documents\Masteroppgave\Matlab\Copy of Tidevannskonstanter.xlsx
%    Worksheet: Harmonic components
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/06 15:10:29

function tideKvalsund =get_tide_Kvalsund()



%% Import the data
[~, ~, raw] = xlsread('\\file.stud.iot.ntnu.no\Home\linnesc\Documents\Masteroppgave\Matlab\Copy of Tidevannskonstanter.xlsx','Harmonic components','L5:O10');

%% Create output variable
tideKvalsund = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;

end